pinaxcon/registrasion/urls.py
from django.conf.urls import url, patterns

import views

urlpatterns = patterns(
    "pinaxcon.registrasion.views",
    url(r"^demopay/([0-9]+)/([A-Z0-9]+)$", views.demopay, name="demopay"),
)

pinaxcon/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from django.contrib.flatpages.views import flatpage

from django.contrib import admin

import symposion.views


urlpatterns = [
    url(r'^saml2/', include('djangosaml2.urls')),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^conference/", include("symposion.conference.urls")),

    url(r"^teams/", include("symposion.teams.urls")),

    # Required by registrasion
    url(r'^tickets/payments/', include('registripe.urls')),
    url(r'^tickets/', include('registrasion.urls')),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^checkin/', include('regidesk.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    url(r'^dashboard/', symposion.views.dashboard, name="dashboard"),
    url(r'^boardingpass', RedirectView.as_view(pattern_name="regidesk:boardingpass")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinaxcon/proposals/models.py
from django.db import models

from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    TARGET_USER = 1
    TARGET_BUSINESS = 2
    TARGET_COMMUNITY = 3
    TARGET_DEVELOPER = 4

    TARGET_AUIDENCES = [
        (TARGET_USER, "User"),
        (TARGET_BUSINESS, "Business"),
        (TARGET_COMMUNITY, "Community"),
        (TARGET_DEVELOPER, "Developer"),
    ]

    target_audience = models.IntegerField(choices=TARGET_AUIDENCES)

    recording_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any recordings of "
        "presentations covered by this proposal, under the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    materials_release = models.BooleanField(
        default=True,
        help_text="I allow Linux Australia to release any other material "
        "(such as slides) from presentations covered by this proposal, under "
        "the <a "
        "href='https://creativecommons.org/licenses/by-sa/3.0/au/deed.en'> "
        "Creative Commons Attribution-Share Alike Australia 3.0 Licence</a>"
    )

    class Meta:
        abstract = True


class TalkProposal(Proposal):

    class Meta:
        verbose_name = "talk proposal"


class TutorialProposal(Proposal):

    class Meta:
        verbose_name = "tutorial proposal"


class MiniconfProposal(Proposal):

    target_audience = models.IntegerField(choices=Proposal.TARGET_AUIDENCES,
                                          default=Proposal.TARGET_DEVELOPER)

    class Meta:
        verbose_name = "miniconf proposal"


class DocsProposal(Proposal):
    TALK_FORMATS = [
        (1, "Presentation (40-45 min)"),
        (2, "Short Presentation (20-30 min)"),
        (3, "Lightning Talk (5-10 min)")
    ]

    talk_format = models.IntegerField(
        choices=TALK_FORMATS,
        help_text="Please indicate your preferred talk length in the private abstract field below.")

    class Meta:
        verbose_name = "Docs Down Under Miniconf Proposal"


class SysAdminProposal(Proposal):

    TYPE_SHORT_PRESENTATION = 1
    TYPE_LIGHTNING_TALK = 2

    TALK_FORMATS = [
        (TYPE_SHORT_PRESENTATION, "Short Presentation (15-25 min)"),
        (TYPE_LIGHTNING_TALK, "Lightning Talk (5-10 min)"),
    ]

    talk_format = models.IntegerField(
        choices=TALK_FORMATS,
        help_text="Please indicate your preferred talk length in the private abstract field below.")

    class Meta:
        verbose_name = "System Administration Miniconf Proposal"


class KernelProposal(Proposal):

    class Meta:
        verbose_name = "Kernel Miniconf Proposal"


class GamesProposal(Proposal):

    TYPE_PRESENTATION = 1
    TYPE_SHORT_PRESENTATION = 2
    TYPE_DEMONSTRATION = 3
    TYPE_OTHER = 4

    TALK_FORMATS = [
        (TYPE_PRESENTATION, "Presentation (long)"),
        (TYPE_PRESENTATION, "Presentation (short)"),
        (TYPE_DEMONSTRATION, "Demonstration"),
        (TYPE_OTHER, "Other"),
    ]

    talk_format = models.IntegerField(choices=TALK_FORMATS)

    class Meta:
        verbose_name = "Games and FOSS Miniconf Proposal"


class OpenHardwareProposal(Proposal):

    TYPE_NORMAL_PRESENTATION = 1
    TYPE_LIGHTNING_TALK = 2

    TALK_FORMATS = [
        (TYPE_NORMAL_PRESENTATION, "Presentation (20 min)"),
        (TYPE_LIGHTNING_TALK, "Lightning Talk (5 min)"),
    ]

    talk_format = models.IntegerField(choices=TALK_FORMATS)

    class Meta:
        verbose_name = "Open Hardware Miniconf Proposal"


class OpenEdProposal(Proposal):

    class Meta:
        verbose_name = "Open Education Miniconf Proposal"


class DevDevProposal(Proposal):

    class Meta:
        verbose_name = "Developers Developers Miniconf Proposal"


class ArtTechProposal(Proposal):

    TYPE_TECH = 1
    TYPE_DEMO = 2
    TYPE_LIGHTNING = 3

    TALK_FORMATS = [
        (TYPE_TECH, "Tech talk (45 min)"),
        (TYPE_DEMO, "Demonstration (20min)"),
        (TYPE_LIGHTNING, "Lightning Talk (10min)"),
    ]

    talk_format = models.IntegerField(
        choices=TALK_FORMATS,
        default=TYPE_TECH,
    )

    EXHIBIT_YES = 1
    EXHIBIT_NO = 2

    EXHIBIT_STATUS = [
        (EXHIBIT_YES, "I am willing and able to exhibit my project on Monday, January 22nd"),
        (EXHIBIT_NO, "I'm unable to exhibit my project")
    ]

    can_exhibit = models.IntegerField(
        choices=EXHIBIT_STATUS,
        default=EXHIBIT_YES,
    )

    exhibition_requirements = models.TextField(
        blank=True,
        default="",
    )

    TARGET_NA = 1

    TARGET_AUDIENCES = [
        (TARGET_NA, "N/A"),
    ]

    target_audience = models.IntegerField(choices=TARGET_AUDIENCES, default=TARGET_NA)

    class Meta:
        verbose_name = "Art+Tech Miniconf Proposal"

pinaxcon/proposals/forms.py
import copy

from django import forms

from pinaxcon.proposals.fields import HelpTextField
from pinaxcon.proposals.models import TalkProposal, TutorialProposal, MiniconfProposal
from pinaxcon.proposals.models import SysAdminProposal, KernelProposal, OpenHardwareProposal
from pinaxcon.proposals.models import GamesProposal, DevDevProposal, ArtTechProposal
from pinaxcon.proposals.models import OpenEdProposal, DocsProposal


DEFAULT_FIELDS =  [
    "title",
    "target_audience",
    "abstract",
    "private_abstract",
    "technical_requirements",
    "project",
    "project_url",
    "recording_release",
    "materials_release",
]

TALK_FORMAT_FIELDS = copy.copy(DEFAULT_FIELDS)
TALK_FORMAT_FIELDS.insert(2, "talk_format")

class ProposalForm(forms.ModelForm):

    required_css_class = 'label-required'

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"The description must be less than 400 characters"
            )
        return value


class DocsProposalForm(ProposalForm):

    class Meta:
        model = DocsProposal
        fields = TALK_FORMAT_FIELDS


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class TutorialProposalForm(ProposalForm):

    class Meta:
        model = TutorialProposal
        fields = [
            "title",
            "target_audience",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "project",
            "project_url",
            "video_url",
            "recording_release",
            "materials_release",
        ]


class MiniconfProposalForm(ProposalForm):

    class Meta:
        model = MiniconfProposal
        fields = [
            "title",
            "abstract",
            "private_abstract",
            "technical_requirements",
            "recording_release",
            "materials_release",
        ]

class SysadminProposalForm(ProposalForm):

    class Meta:
        model = SysAdminProposal
        fields = TALK_FORMAT_FIELDS

class KernelProposalForm(ProposalForm):

    class Meta:
        model = KernelProposal
        fields = DEFAULT_FIELDS


class GamesProposalForm(ProposalForm):

    HELP_TEXT = ("If you have <strong>any</strong> questions please contact "
        "the games miniconf organisers. We're excited to hear from you! You "
        "can reach us via email <a href=\"mailto:games@lca.lonely.coffee\">"
        "games@lca.lonely.coffee</a> or twitter DM <a href=\"https://twitter"
        ".com/ducky_tape\" ref=\"noreferrer noopener\" target=\"_blank\">"
        "@ducky_tape</a> and <a href=\"https://twitter.com/the_mcjones\" "
        "ref=\"noreferrer noopener\" target=\"_blank\">@the_mcjones</a>.")

    help_field = HelpTextField(text=HELP_TEXT, label='')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['private_abstract'].help_text = ("it would be helpful if "
            "you could please include a <strong>rough</strong> (don't worry, "
            "we know it might change!) Outline of your presentation, e.g. "
            "'0-2mins intro, 2-5mins the problem, 5-10mins things, 10-15mins "
            "stuff 15-20mins solution'.")

    class Meta:
        model = GamesProposal
        fields = ['help_field', ] + TALK_FORMAT_FIELDS

class OpenHardwareProposalForm(ProposalForm):

    class Meta:
        model = OpenHardwareProposal
        fields = TALK_FORMAT_FIELDS

class OpenEdProposalForm(ProposalForm):

    class Meta:
        model = OpenEdProposal
        fields = DEFAULT_FIELDS

class DevDevProposalForm(ProposalForm):

    class Meta:
        model = DevDevProposal
        fields = DEFAULT_FIELDS

class ArtTechProposalForm(ProposalForm):

    class Meta:
        ARTTECH_FIELDS = copy.copy(DEFAULT_FIELDS)
        ARTTECH_FIELDS.remove("target_audience")
        ARTTECH_FIELDS.append("talk_format")
        ARTTECH_FIELDS.append("can_exhibit")
        ARTTECH_FIELDS.append("exhibition_requirements")

        model = ArtTechProposal
        fields = ARTTECH_FIELDS

pinaxcon/registrasion/forms.py
from pinaxcon.registrasion import models

from django import forms


class YesNoField(forms.TypedChoiceField):

    def __init__(self, *args, **kwargs):
        kwargs['required'] = True
        super(YesNoField, self).__init__(
            *args,
            coerce=lambda x: x in ['True', 'Yes', True],
            choices=((None, '--------'), (False, 'No'), (True, 'Yes')),
            **kwargs
        )


class ProfileForm(forms.ModelForm):
    ''' A form for requesting badge and profile information. '''

    required_css_class = 'label-required'

    class Meta:
        model = models.AttendeeProfile
        exclude = ['attendee']
        widgets = {
            'past_lca': forms.widgets.CheckboxSelectMultiple
        }
        field_classes = {
            "of_legal_age": YesNoField,
        }

pinaxcon/registrasion/views.py
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from registrasion import models as rego
from registrasion.controllers.invoice import InvoiceController

from pinaxcon.registrasion import models


def demopay(request, invoice_id, access_code):
    ''' Marks the invoice with the given invoice id as paid.
    '''
    invoice_id = int(invoice_id)
    inv = get_object_or_404(rego.Invoice.objects, pk=invoice_id)

    invoice = InvoiceController(inv)

    if not invoice.can_view(user=request.user, access_code=access_code):
        raise Http404()

    to_invoice = redirect("invoice", invoice.invoice.id, access_code)

    try:
        invoice.validate_allowed_to_pay()  # Verify that we're allowed to do this.
    except ValidationError as ve:
        messages.error(request, ve.message)
        return to_invoice

    # Create the payment object
    models.DemoPayment.objects.create(
        invoice=invoice.invoice,
        reference="Demo payment by user: " + request.user.username,
        amount=invoice.invoice.value,
    )

    invoice.update_status()

    messages.success(request, "This invoice was successfully paid.")

    return to_invoice

pinaxcon/views.py
from django.shortcuts import render, redirect

from account.decorators import login_required
from symposion.proposals.models import ProposalSection


@login_required
def dashboard(request):
    """
    Copy of symposion.views.dashboard modified to inject available proposal
    kinds into the request context.
    """

    if request.session.get("pending-token"):
        return redirect("speaker_create_token", request.session["pending-token"])


    sections = ProposalSection.available().prefetch_related('section__proposal_kinds')
    kinds = [k for kind in section for k in section.proposal_kinds]
    return render(request, "dashboard.html", {'kinds': kinds})

pinaxcon/templates/symposion/reviews/_result_notification_prepare_help.html
    <b>Body</b> may include the following variables which will be substituted in the email with a value
    specific to each proposal:
<ul>
    <li><code>{% templatetag openvariable %} proposal.title {% templatetag closevariable %}</code> e.g. {{ proposals.0.title }}
    <li><code>{% templatetag openvariable %} proposal.kind {% templatetag closevariable %}</code> e.g. {{ proposals.0.kind }}
    <li><code>{% templatetag openvariable %} proposal.main_speaker {% templatetag closevariable %}</code> e.g. {{ proposals.0.speaker }}
    <li><code>{% templatetag openvariable %} proposal.speakers {% templatetag closevariable %}</code> e.g. {{ proposals.0.speakers|join:", " }}
    <li><code>{% templatetag openvariable %} proposal.additional_speakers {% templatetag closevariable %}</code> e.g. {{ proposals.0.additional_speakers }}
</ul>

pinaxcon/templates/symposion/reviews/_review_table.html
{% load i18n %}

<table class="table table-striped table-reviews">
    <thead>
        <th>#</th>
        <th>{% trans "Speaker / Title" %}</th>
        <th class="toggle">Withdrawn?</th>
        <th class="toggle">Audience</th>
        <th class="toggle">Format</th>
        <th>{% trans "Votes" %}</th>
        <th class="toggle">{% trans "Score" %}</th>
        <th class="votes">{% trans "+2" %}</th>
        <th class="votes">{% trans "+1" %}</th>
        <th class="votes">{% trans "-1" %}</th>
        <th class="votes">{% trans "-2" %}</th>
        <th><a href="#" class="tip" title="{% trans "Your Rating" %}"><i class="oi oi-person"></i></a></th>
    </thead>

    <tbody>
        {% for proposal in proposals %}
            <tr class="{{ proposal.user_vote_css }}">
                <td>{{ proposal.number }}</td>
                <td>
                    <a href="{% url "review_detail" proposal.pk %}">
                        <small><strong>{{ proposal.speaker }}</strong></small>
                        <br />
                        {{ proposal.title }}
                    </a>
                </td>
                <td>
                    {% if proposal.cancelled %}
                        <p class="badge-danger">WITHDRAWN</p>
                    {% else %}
                        <p class="badge-success">Not withdrawn</p>
                    {% endif %}</td>
                <td>{{ proposal.get_target_audience_display }}</td>
                <td>{{ proposal.get_talk_format_display }}</td>
                <td>{{ proposal.total_votes }}</td>
                <td>{{ proposal.score }}</td>
                <td>{{ proposal.plus_two }}</td>
                <td>{{ proposal.plus_one }}</td>
                <td>{{ proposal.minus_one }}</td>
                <td>{{ proposal.minus_two }}</td>
                <td>{{ proposal.user_vote|default:"" }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

pinaxcon/templates/symposion/reviews/access_not_permitted.html
{% extends "symposion/reviews/base.html" %}

{% block body %}
    <h1>Access Not Permitted</h1>

    <p>
        Sorry, you do not have permission to access this page. If you
        believe this is a bug, please contact us immediately.
    </p>
{% endblock %}

pinaxcon/templates/symposion/reviews/base.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% load i18n %}

{% block body_class %}reviews{% endblock %}

{% block body_outer %}
<div class="text-primary">
    <div class="sidebar-wrapper">
        <div class="sidebar mr-5">
            <div class="collapser mb-3">
                <div id="sidebarBtn"><span class="oi oi-menu"></span></div>
            </div>
            {% block sidebar %}
            {% for section in review_sections %}

            <div class="card card-default mb-3">
                <div class="card-header">
                    <h3 class="card-title">{{ section }}</h3>
                </div>
                <div class="list-group">
                    <a class="list-group-item review-list" href="{% url "review_section" section.section.slug %}">
                        {% trans "All Reviews" %}
                    </a>
                    {% comment %}
                    <li>
                        <a href="{% url "review_section_assignments" section.section.slug %}">
                            {% trans "Your Assignments" %}
                        </a>
                    </li>
                    {% endcomment %}
                    <a class="list-group-item user-reviewed" href="{% url "user_reviewed" section.section.slug %}">
                        {% trans "Reviewed by you" %}
                    </a>
                    <a class="list-group-item user-not-reviewed" href="{% url "user_not_reviewed" section.section.slug %}">
                        {% trans "Unreviewed by you" %}
                    </a>
                    <a class="list-group-item user-random" href="{% url "user_random" section.section.slug %}">
                        {% trans "Random unreviewed proposal" %}
                    </a>
                    <a class="list-group-item voting-status" href="{% url "review_status" section.section.slug %}">
                        {% trans "Voting Status" %}
                    </a>
                    {% if request.user.is_staff %}
                    <a class="list-group-item review-results" href="{% url "result_notification" section.section.slug 'accepted' %}">Result Notification</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
            {% endblock %}
        </div>
        <div style="flex: 1 1 0; min-width: 40px;">
            {% block body %}
            {% endblock %}
        </div>
    </div>
</div>

{% endblock %}
{% block extra_script %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.2/b-colvis-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fc-3.2.5/fh-3.1.4/kt-2.4.0/r-2.2.2/rg-1.0.3/rr-1.2.4/datatables.min.css"/>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="//cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.2/b-colvis-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fc-3.2.5/fh-3.1.4/kt-2.4.0/r-2.2.2/rg-1.0.3/rr-1.2.4/datatables.min.js"></script>
<script type="text/javascript">
    var reviewtable = $("table.table-reviews").DataTable({
        "stateSave": true,
        "autoWidth": false,
        "lengthMenu": [[10, 50, 100, -1], [10, 50, 100, "All"]],
        "pageLength": 100,
        "colReorder": true,
         "columnDefs": [
            { targets: [6,7,8,9,10], visible: false}
        ],  
        "buttons": [{
              extend: 'collection',
              text: 'Export',
              buttons: ["copy", "csv", "print"]
            },
            { extend: 'collection',
              text: 'Columns',
              buttons: [
                { extend: 'columnsToggle',
                  columns: '.toggle' },
                { extend: 'columnToggle',
                  text: 'Vote details',
                  columns: '.votes'
    }]}]});
    reviewtable.buttons().container().prependTo( $(reviewtable.table().container() ));
</script>
<script>
$(document).ready(function () {

$('#sidebarBtn').on('click', function () {
    $('.sidebar').toggleClass('active');
});

});
</script>
{% endblock %}

pinaxcon/templates/symposion/reviews/result_notification_prepare.html
{% extends "symposion/reviews/base.html" %}

{% load i18n %}

{% block body %}
    <h1>Result Notification Prepare</h1>

    <div class="row">
        <div class="col-md-4">
            <h2>Proposals</h2>
            <table class="table table-striped table-compact">
                {% for proposal in proposals %}
                    <tr>
                        <td>
                            <strong>{{ proposal.speaker }}</strong> ({{ proposal.speaker.email }})
                            <br />
                            {{ proposal.title }}
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-md-6">
            <h2>Email</h2>

            <form class="form-horizontal" method="post" action="{% url "result_notification_send" section_slug status %}">

                {% csrf_token %}

                <label>From Address</label>
                <input type="text" name="from_address" class="span5" value="{{ notification_template.from_address }}" />
                <br/>
                <label>Subject</label>
                <input type="text" name="subject" class="span5" value="{{ notification_template.subject }}" />
                <br/>
                <label>Body</label>
                <textarea class="span5" rows="10" name="body">{{ notification_template.body }}</textarea>
                <br/>
                <input type="hidden" name="notification_template" value="{{ notification_template.pk }}" />
                <input type="hidden" name="proposal_pks" value="{{ proposal_pks }}" />

                {% include "symposion/reviews/_result_notification_prepare_help.html" %}

                <button type="submit" class="btn btn-primary">Send {{ proposals|length }} Email{{ proposals|length|pluralize }}</button>
                <a class="btn" href="{% url "result_notification" section_slug status %}">Cancel</a>
            </form>
        </div>
    </form>
{% endblock %}

pinaxcon/templates/symposion/reviews/review_admin.html
{% extends "symposion/reviews/base.html" %}

{% block body %}
    <h1>Reviewers – {{ section_slug }}</h1>

    <table class="table table-striped">
        <tr>
            <th>
                Reviewer
            </th>
            <th>
                Proposals<br/>Reviewed
            </td>
            <th>
                Comments
            </th>
            <th>
                Avg
            </th>
            <th>
                +2
            </th>
            <th>
                +1
            </th>
            <th>
                &minus;1
            </th>
            <th>
                &minus;2
            </th>
            <th>
                Abstain
            </th>
        </tr>
        {% for reviewer in reviewers %}
        <tr>
            <td>
                <a href="{% url "review_list_user" section_slug reviewer.pk %}">
                    {{ reviewer.get_full_name }} &lt;{{ reviewer.email }}&gt;
                </a>
            </td>
            <td>
                {{ reviewer.total_votes }}
            </td>
            <td>
                {{ reviewer.comment_count }}
            </td>
            <td>
                {{ reviewer.average|floatformat:2 }}
            </td>
            <td>
                {{ reviewer.plus_two }}
            </td>
            <td>
                {{ reviewer.plus_one }}
            </td>
            <td>
                {{ reviewer.minus_one }}
            </td>
            <td>
                {{ reviewer.minus_two }}
            </td>
            <td>
                {{ reviewer.abstain }}
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

pinaxcon/templates/symposion/reviews/review_assignment.html
{% extends "symposion/reviews/base.html" %}

{% block body %}
    <h1>Review Assignments</h1>

    {% if assignments %}
        <table>
            <tr>
                <th>Proposal</th>
                <th>Opted out</th>
                <th>Opt out</th>
            </tr>
            {% for assignment in assignments %}
                <tr>
                    <td>
                        <a href="{% url review_detail assignment.proposal.pk %}">
                            {{ assignment.proposal.title }}
                        </a>
                    </td>
                    <td>
                        <form class="form-horizontal" method="post" action="{% url "review_assignment_opt_out" assignment.pk %}">
                            {% csrf_token %}
                            <input type="submit" value="Opt-out" />
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>You do not have any assignments.</p>
    {% endif %}
{% endblock %}

pinaxcon/templates/symposion/reviews/review_bulk_update.html
{% extends "symposion/reviews/base.html" %}

{% load bootstrap %}

{% block body %}

    <h1>Bulk Accept</h1>
    <form class="form-horizontal" action="" method="POST" class="uniForm" accept-charset="utf-8">
        {% csrf_token %}
        {{ form|bootstrap }}
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" name="submit" value="submit" />
        </div>
    </form>
{% endblock %}

pinaxcon/templates/symposion/reviews/review_comment.html
{{ proposal }}: proposal obj
{{ form }}: comment form obj

pinaxcon/templates/symposion/reviews/review_list.html
{% extends "symposion/reviews/base.html" %}


{% block body_class %}{{ block.super }}
	{% if reviewed == "all_reviews" %}
		review-list
	{% endif %}
{% endblock %}

{% block body %}
	<h3>{{ section }}</h3>
	{% if reviewed == 'all_reviews' %}
    	<h4>All proposals</h4>
    {% elif reviewed == 'user_reviewed' %}
    	<h4>Proposals you have reviewed</h4>
    {% else %}
    	<h4>Proposals you have not yet reviewed</h4>
    {% endif %}

    {% include "symposion/reviews/_review_table.html" %}
{% endblock %}